# -*- coding: utf-8 -*-
"""Streamlit_Ejemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1URCBVLYSt8kzGfVlYF4JgrMSCtu3WGLG
"""

import streamlit as st

st.write('Hello, World!,:sunglasses:')